### ISSUE TITLE
Get-SDMGPOSecurity - Class Not Registered Error

### ISSUE THREAD

**Issue by forensic65x** [gpoguy/GetVulnerableGPO#4]
I am receiving the following error. Any suggestions on a fix?

Get-SDMGPOSecurity : Retrieving the COM class factory for component with CLSID {F5694708-88FE-4B35-BABF-E56162D5FBC8}
failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154
(REGDB_E_CLASSNOTREG)).
At [path]\GetVulnerableGPO\Get-VulnerableGPO.ps1:141 char:22
+ ...    $perms = Get-SDMGPOSecurity -DisplayName $foundGPO.Attributes["dis ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Workstations LclAdm:String) [Get-SDMgpoSecurity], COMException
    + FullyQualifiedErrorId : Retrieving the COM class factory for component with CLSID {F5694708-88FE-4B35-BABF-E5616
   2D5FBC8} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REG
  DB_E_CLASSNOTREG)).,Sdmsoftware.PS.Commands.getSDMgposecurityCommand

Out-SDMGPSettings : Retrieving the COM class factory for component with CLSID {F5694708-88FE-4B35-BABF-E56162D5FBC8}
failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154
(REGDB_E_CLASSNOTREG)).
At [path]\GetVulnerableGPO\Get-VulnerableGPO.ps1:157 char:25
+ ... $settings = Out-SDMGPSettings -Domain $Domain -DisplayName $foundGPO. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Out-SDMGPSettings], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,SdmSoftware.PS.Commands.OutSDMGPSettings

**Comment by gpoguy** [comment]
Apologies for not seeing this sooner. Typically this message means that GPMC is not installed on the machine running the script. That's a pre-requisite for the script and the SDM-GPMC Posh module
